# Generated by Django 4.1.2 on 2022-10-20 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('didConfiguration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='didconfiguration',
            name='context',
            field=models.CharField(default='0000000', editable=False, max_length=200),
        ),
    ]
